# FILES := $(shell git diff --name-only --diff-filter=AM $$(git merge-base origin/main HEAD) -- \*.py)

.PHONY: precheck
precheck:
	zsh -c ./scripts/precheck.sh

.PHONY: setup
setup: precheck
	mkdir -p .venv
	pipenv sync -d
	pipenv run pre-commit install

.PHONY: test
test: precheck
	pipenv run pytest -vv --disable-warnings --junit-xml=coverage.xml --cov=slingshot tests/

.PHONY: check
format: precheck
	pipenv run pre-commit run -a

# Removes the directory that contains bytecode cache files
# that are automatically generated by python.
.PHONY: clean
clean:
	find . -type f -name "*.pyc" | xargs rm -fr
	find . -type d -name __pycache__ | xargs rm -fr
	find . -type d -name ".ruff_cache" | xargs rm -fr
	pipenv clean
	pipenv sync -d