name: Update Changelog

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Commitzen next-version (dry-run)
        id: bump-version
        run: |
          OUTPUT=$(uv run cz bump --yes --get-next)
          echo "BUMP_OUTPUT=$OUTPUT" >> $GITHUB_OUTPUT
          uv run cz bump --yes --files-only
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Release ${{ steps.bump-version.outputs.BUMP_OUTPUT }}"
          body: |
            This pull request bumps the version to ${{ steps.bump-version.outputs.BUMP_OUTPUT }} and updates the changelog.
          base: main
          head: release-${{ steps.bump-version.outputs.BUMP_OUTPUT }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            release: ${{ steps.bump-version.outputs.BUMP_OUTPUT }}
